### ISSUE TITLE
Uncaught Error: EACCES: permission denied, scandir '~/Library/Saved Application State/com.adobe.f...

### ISSUE THREAD

**Issue by esousa77** [mybuddymichael/linter-elm-make#108]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [linter-elm-make](https://github.com/mybuddymichael/linter-elm-make) package, v0.18.2

### Stack Trace

Uncaught Error: EACCES: permission denied, scandir '/Users/edvansousa/Library/Saved Application State/com.adobe.flashplayer.installmanager.savedState'

```
At fs.js:951

Error: EACCES: permission denied, scandir '/Users/edvansousa/Library/Saved Application State/com.adobe.flashplayer.installmanager.savedState'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:571:28)
    at copySync (/Users/edvansousa/.atom/packages/linter-elm-make/node_modules/fs-extra/lib/copy-sync/copy-sync.js:36:23)
    at /Users/edvansousa/.atom/packages/linter-elm-make/node_modules/fs-extra/lib/copy-sync/copy-sync.js:40:7
    at Array.forEach (native)
    at copySync (/Users/edvansousa/.atom/packages/linter-elm-make/node_modules/fs-extra/lib/copy-sync/copy-sync.js:37:14)
    at /Users/edvansousa/.atom/packages/linter-elm-make/node_modules/fs-extra/lib/copy-sync/copy-sync.js:40:7
    at Array.forEach (native)
    at copySync (/Users/edvansousa/.atom/packages/linter-elm-make/node_modules/fs-extra/lib/copy-sync/copy-sync.js:37:14)
    at /Users/edvansousa/.atom/packages/linter-elm-make/node_modules/fs-extra/lib/copy-sync/copy-sync.js:40:7
    at Array.forEach (native)
    at Object.copySync (/Users/edvansousa/.atom/packages/linter-elm-make/node_modules/fs-extra/lib/copy-sync/copy-sync.js:37:14)
    at /Users/edvansousa/.atom/packages/linter-elm-make/lib/linter-elm-make.js:472:20
    at Set.forEach (native)
    at /Users/edvansousa/.atom/packages/linter-elm-make/lib/linter-elm-make.js:460:35
    at /Users/edvansousa/.atom/packages/linter-elm-make/lib/linter-elm-make.js:480:14
```

### Commands

```
 14x -5:54.2.0 blur (atom-pane.pane.active)
     -5:47 settings-view:open (input.hidden-input)
 16x -5:46.6.0 blur (input.hidden-input)
     -5:37 core:confirm (input.hidden-input)
 25x -5:29.3.0 blur (input.hidden-input)
     -4:00.2.0 core:save (input.hidden-input)
  3x -3:47.1.0 blur (input.hidden-input)
     -3:47 linter:lint (atom-text-editor.editor.is-focused)
  6x -0:00.0 blur (input.hidden-input)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited"
  },
  "linter-elm-make": {
    "alwaysCompileMain": true,
    "elmMakeExecutablePath": "/usr/local/bin/elm-make",
    "lintOnTheFly": true
  }
}
```

### Installed Packages

```coffee
# User
elm-format, v2.1.0 (active)
language-elm, v1.5.0 (active)
linter, v1.11.21 (active)
linter-elm-make, v0.18.2 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by halohalospecial** [comment]
Hi @esousa77, can you also provide the contents of your `elm-package.json`?  Thanks!
