### ISSUE TITLE
Failed to load the linter-elm-make package

### ISSUE THREAD

**Issue by pruett** [mybuddymichael/linter-elm-make#135]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [linter-elm-make](https://github.com/mybuddymichael/linter-elm-make) package 0.23.0

### Stack Trace

Failed to load the linter-elm-make package

```
At Cannot find module 'fs-extra'

Error: Cannot find module 'fs-extra'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/linter-elm-make/lib/linter-elm-make.js:4:24)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at /app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/app.asar/src/package-manager.js:407:19)
    at /app.asar/src/atom-environment.js:792:28
```

### Commands

```
     -1:04.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-light-ui)
```

### Non-Core Packages

```
aligner 0.22.3 
blame 0.10.2 
busy-signal 1.3.0 
editorconfig 2.2.2 
elm-format 2.1.0 
elmjutsu 5.3.3 
file-icons 2.0.17 
git-plus 7.3.3 
intentions 1.1.2 
language-cjsx 0.3.0 
language-elm 1.5.0 
language-javascript-jsx 0.3.7 
linter 2.1.0 
linter-elm-make 0.23.0 
linter-ui-default 1.1.0 
merge-conflicts 1.4.4 
prettier-atom 0.23.0 
relative-numbers 0.7.1 
vim-mode-plus 0.84.1 
```

**Comment by halohalospecial** [comment]
@pruett, try reinstalling `linter-elm-make`, then restart Atom.

**Comment by pruett** [comment]
that seemed to do it @halohalospecial .. thanks!
