### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, symlink '~/kod/DATX02-18-07/tests/elm-stuff' -> '/tm...

### ISSUE THREAD

**Issue by sutbult** [mybuddymichael/linter-elm-make#177]
[Enter steps to reproduce:]

1. Use elm-test (https://github.com/deadfoxygrandpa/Elm-Test) with this plugin
2. This error starts to appear all the time 

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Linux Mint
**Thrown From**: [linter-elm-make](https://github.com/mybuddymichael/linter-elm-make) package 0.28.1

### Stack Trace

Uncaught Error: EEXIST: file already exists, symlink '/path/to/project/tests/elm-stuff' -> '/tmp/linter-elm-make27019HqVN92qY35bR/elm-stuff/generated-code/elm-community/elm-test/elm-stuff'

```
At fs.js:1044

Error: EEXIST: file already exists, symlink '/path/to/project/tests/elm-stuff' -> '/tmp/linter-elm-make27019HqVN92qY35bR/elm-stuff/generated-code/elm-community/elm-test/elm-stuff'
    at Object.fs.symlinkSync (fs.js:1044:18)
    at copySync (/packages/linter-elm-make/node_modules/fs-extra/lib/copy-sync/copy-sync.js:44:8)
    at /packages/linter-elm-make/node_modules/fs-extra/lib/copy-sync/copy-sync.js:40:7
    at Array.forEach (native)
    at copySync (/packages/linter-elm-make/node_modules/fs-extra/lib/copy-sync/copy-sync.js:37:14)
    at /packages/linter-elm-make/node_modules/fs-extra/lib/copy-sync/copy-sync.js:40:7
    at Array.forEach (native)
    at copySync (/packages/linter-elm-make/node_modules/fs-extra/lib/copy-sync/copy-sync.js:37:14)
    at /packages/linter-elm-make/node_modules/fs-extra/lib/copy-sync/copy-sync.js:40:7
    at Array.forEach (native)
    at copySync (/packages/linter-elm-make/node_modules/fs-extra/lib/copy-sync/copy-sync.js:37:14)
    at /packages/linter-elm-make/node_modules/fs-extra/lib/copy-sync/copy-sync.js:40:7
    at Array.forEach (native)
    at Object.copySync (/packages/linter-elm-make/node_modules/fs-extra/lib/copy-sync/copy-sync.js:37:14)
    at /packages/linter-elm-make/lib/linter-elm-make.js:820:14
```

### Commands

```
  2x -0:29.8.0 linter:lint (atom-text-editor.editor)
     -0:11.7.0 intentions:highlight (input.hidden-input)
     -0:11.7.0 core:copy (input.hidden-input)
     -0:10.6.0 linter:lint (atom-text-editor.editor)
     -0:09.3.0 intentions:highlight (input.hidden-input)
     -0:09.3.0 core:paste (input.hidden-input)
     -0:08.5.0 intentions:highlight (input.hidden-input)
     -0:08.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
intentions 1.1.5 
language-elm 1.5.0 
language-erlang 3.2.0 
language-haskell 1.17.3 
linter 2.2.0 
linter-elm-make 0.28.1 
linter-ui-default 1.7.1 
```

**Comment by renanpvaz** [comment]
@sutbult were you able to fix this issue?
