### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, scandir '~/Library/Application Support/AddressBook'

### ISSUE THREAD

**Issue by matthijsl** [mybuddymichael/linter-elm-make#189]
Not so much an issue, more of a question as to why my AddressBook needs to be scanned?

1. Open Atom
2. Open an Elm project
3. Open Main.elm

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.2
**Thrown From**: [linter-elm-make](https://github.com/mybuddymichael/linter-elm-make) package 0.29.0

### Stack Trace

Uncaught Error: EPERM: operation not permitted, scandir '/Users/matthijsliethof/Library/Application Support/AddressBook'

```
At fs.js:904

Error: EPERM: operation not permitted, scandir '/Users/matthijsliethof/Library/Application Support/AddressBook'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:608:28)
    at copySync (/packages/linter-elm-make/node_modules/fs-extra/lib/copy-sync/copy-sync.js:36:23)
    at /packages/linter-elm-make/node_modules/fs-extra/lib/copy-sync/copy-sync.js:40:7
    at Array.forEach (<anonymous>)
    at copySync (/packages/linter-elm-make/node_modules/fs-extra/lib/copy-sync/copy-sync.js:37:14)
    at /packages/linter-elm-make/node_modules/fs-extra/lib/copy-sync/copy-sync.js:40:7
    at Array.forEach (<anonymous>)
    at copySync (/packages/linter-elm-make/node_modules/fs-extra/lib/copy-sync/copy-sync.js:37:14)
    at /packages/linter-elm-make/node_modules/fs-extra/lib/copy-sync/copy-sync.js:40:7
    at Array.forEach (<anonymous>)
    at Object.copySync (/packages/linter-elm-make/node_modules/fs-extra/lib/copy-sync/copy-sync.js:37:14)
    at /packages/linter-elm-make/lib/linter-elm-make.js:905:20
    at Set.forEach (<anonymous>)
    at /packages/linter-elm-make/lib/linter-elm-make.js:874:35
    at /packages/linter-elm-make/lib/linter-elm-make.js:923:14
```

### Commands

```
     -5:57.4.0 linter:lint (atom-text-editor.editor.vim-mode-plus.normal-mode)
     -5:56.7.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.4 
atom-debug-ui 1.0.4 
atom-elixir 0.2.3 
atom-ide-ui 0.13.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-typescript 13.1.0 
autoclose-html 0.23.0 
autocomplete-solidity 0.3.4 
busy-signal 2.0.0 
elm-format 3.2.0 
elmjutsu 9.10.1 
gruvbox 1.0.7 
hasklig 0.4.0 
ide-php 0.7.18 
intentions 1.1.5 
language-docker 1.1.8 
language-elm 1.5.0 
language-ethereum 0.3.9 
linter 2.3.0 
linter-elm-make 0.29.0 
linter-php 1.6.0 
linter-ui-default 1.7.1 
php-debug 0.3.5 
pigments 0.40.2 
relative-numbers 0.9.0 
vim-mode-plus 1.36.0 
```

**Comment by halohalospecial** [comment]
Hi, it looks for the `elm-package.json` file starting from the directory where the active file is.  Maybe you don't have an `elm-package.json` file?

If you're using Elm 0.19, however, you should use https://atom.io/packages/elmjutsu instead because linter-elm-make only supports Elm 0.18.

**Comment by matthijsl** [comment]
> If you're using Elm 0.19, however, you should use https://atom.io/packages/elmjutsu instead because linter-elm-make only supports Elm 0.18.

This was indeed the case. Thank you!
